### ISSUE TITLE
Getting angular error

### ISSUE THREAD

**Issue by quicksilverr** [codephobia/nx-loopback-next#13]
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:464:13)
    at /Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/symplrr/Desktop/Projects/Backend/zonocloud/node_modules/@angular-devkit/core/node

**Comment by quicksilverr** [comment]
@codephobia
